<?php

namespace Database\Seeders;

use App\Models\Product;
use Haruncpi\LaravelIdGenerator\IdGenerator;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = collect([
            [
                'name' => 'Passive Infrared Sensor',
                'slug' => 'passive-infrared-sensor',
                'code' => '001',
                // 'quantity' => 10,
                'buying_price' => 900,
                'selling_price' => 1400,
                'quantity_alert' => 10,
                'tax' => 24,
                'tax_type' => 1,
                'notes' => null,
                'category_id' => 1,
                'unit_id' => 3,
            ],
            [
                'name' => 'HP LaserJet Pro MFP M428fdw',
                'slug' => 'hp-laserjet-pro-mfp-m428fdw',
                'code' => '002',
                // 'quantity' => 10,
                'buying_price' => 900,
                'selling_price' => 1400,
                'quantity_alert' => 10,
                'tax' => 24,
                'tax_type' => 1,
                'notes' => null,
                'category_id' => 2,
                'unit_id' => 3,
            ],
            [
                'name' => 'Canon ImageFormula DR-C225',
                'slug' => 'canon-imageformula-dr-c225',
                'code' => '003',
                // 'quantity' => 10,
                'buying_price' => 900,
                'selling_price' => 1400,
                'quantity_alert' => 10,
                'tax' => 24,
                'tax_type' => 1,
                'notes' => null,
                'category_id' => 3,
                'unit_id' => 3,
            ],
            [
                'name' => 'Dell PowerEdge R740 Rack Server',
                'slug' => 'dell-poweredge-r740-rack-server',
                'code' => '004',
                // 'quantity' => 10,
                'buying_price' => 900,
                'selling_price' => 1400,
                'quantity_alert' => 10,
                'tax' => 24,
                'tax_type' => 1,
                'notes' => null,
                'category_id' => 4,
                'unit_id' => 3,
            ],
            [
                'name' => 'Seagate 2TB External Hard Drive',
                'slug' => 'seagate-2tb-external-hard-drive',
                'code' => '005',
                // 'quantity' => 10,
                'buying_price' => 900,
                'selling_price' => 1400,
                'quantity_alert' => 10,
                'tax' => 24,
                'tax_type' => 1,
                'notes' => null,
                'category_id' => 5,
                'unit_id' => 3,
            ],
            [
                'name' => 'APC Smart-UPS 1500VA',
                'slug' => 'apc-smart-ups-1500va',
                'code' => '006',
                // 'quantity' => 10,
                'buying_price' => 900,
                'selling_price' => 1400,
                'quantity_alert' => 10,
                'tax' => 24,
                'tax_type' => 1,
                'notes' => null,
                'category_id' => 6,
                'unit_id' => 3,
            ],
            [
                'name' => 'TP-Link Cat6 Ethernet Cable (100m)',
                'slug' => 'tp-link-cat6-ethernet-cable-100m',
                'code' => '007',
                // 'quantity' => 10,
                'buying_price' => 900,
                'selling_price' => 1400,
                'quantity_alert' => 10,
                'tax' => 24,
                'tax_type' => 1,
                'notes' => null,
                'category_id' => 7,
                'unit_id' => 3,
            ],
            [
                'name' => 'Fluke Networks Cable Tester',
                'slug' => 'fluke-networks-cable-tester',
                'code' => '008',
                // 'quantity' => 10,
                'buying_price' => 900,
                'selling_price' => 1400,
                'quantity_alert' => 10,
                'tax' => 24,
                'tax_type' => 1,
                'notes' => null,
                'category_id' => 8,
                'unit_id' => 3,
            ],
            [
                'name' => 'Wi-Fi 6 Mesh Router Pro',
                'slug' => 'wi-fi-6-mesh-router-pro',
                'code' => '012',
                // 'quantity' => 10,
                'buying_price' => 900,
                'selling_price' => 1400,
                'quantity_alert' => 10,
                'tax' => 24,
                'tax_type' => 1,
                'notes' => null,
                'category_id' => 9,
                'unit_id' => 3,
            ],
            [
                'name' => 'CyberGuard X Firewall',
                'slug' => 'cyberguard-x-firewall',
                'code' => '013',
                // 'quantity' => 10,
                'buying_price' => 900,
                'selling_price' => 1400,
                'quantity_alert' => 10,
                'tax' => 24,
                'tax_type' => 1,
                'notes' => null,
                'category_id' => 10,
                'unit_id' => 3,
            ],
            [
                'name' => 'Digital Thermometer',
                'slug' => 'digital-thermometer',
                'code' => '009',
                // 'quantity' => 10,
                'buying_price' => 900,
                'selling_price' => 1400,
                'quantity_alert' => 10,
                'tax' => 24,
                'tax_type' => 1,
                'notes' => null,
                'category_id' => 11,
                'unit_id' => 3,
            ],
            [
                'name' => 'Logitech Wireless Mouse',
                'slug' => 'logitech-wireless-mouse',
                'code' => '010',
                // 'quantity' => 10,
                'buying_price' => 900,
                'selling_price' => 1400,
                'quantity_alert' => 10,
                'tax' => 24,
                'tax_type' => 1,
                'notes' => null,
                'category_id' => 12,
                'unit_id' => 3,
            ],
            [
                'name' => 'Bic Cristal Ballpoint Pen',
                'slug' => 'bic-cristal-ballpoint-pen',
                'code' => '011',
                // 'quantity' => 10,
                'buying_price' => 900,
                'selling_price' => 1400,
                'quantity_alert' => 10,
                'tax' => 24,
                'tax_type' => 1,
                'notes' => null,
                'category_id' => 13,
                'unit_id' => 3,
            ],
        ]);

        $products->each(function ($product) {
            Product::create($product);
        });
    }
}
